package server

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"
	"strings"
	"time"

	"github.com/calvinchengx/fabric-emulator/internal/store"
)

// DefaultEventKeepalive is how often an idle flow stream emits an SSE comment.
//
// It uses **wall** time deliberately: this is a transport concern, unlike
// everything the emulator *models*, which runs on the controllable clock.
//
// It also bounds something less obvious. A handler parked in select does not
// observe a client hang-up until it next tries to write — that is ordinary SSE
// behaviour, not a bug — so this interval is the worst case for how long a
// vanished subscriber lingers. One goroutine and one buffered channel, reaped
// on the next tick. Tests set Server.EventKeepalive low so they need not wait
// it out.
const DefaultEventKeepalive = 15 * time.Second

// registerEvents mounts the flow stream.
//
// Server-Sent Events rather than a WebSocket: the stream is one-way, `curl -N`
// tails it with no client at all (the biggest quality-of-life win here needs no
// portal), browsers reconnect on their own via EventSource, and it costs no new
// dependency.
//
// It lives under /_emulator — the testing-lever namespace beside the clock and
// the fault injector — because real Fabric has no such endpoint. This is an
// emulator-only surface and docs/parity.md records it as one.
func (s *Server) registerEvents() {
	s.mux.HandleFunc("GET /_emulator/events", s.emulatorEvents)
}

// parseKindFilter reads the `?kinds=` parameter into a set, and reports any name
// that is not a kind this bus carries.
//
// EXTRACTED to be testable, and validating because it can be: store.AllKinds is
// the contract, so an unrecognised name is answerable rather than something to
// pass through and hope about.
//
// An ABSENT or empty parameter yields a nil set, which the caller reads as
// "everything" — deliberately, because `?kinds=` should not mean "nothing" and
// silently produce a dead stream.
//
// KindDropped is always admitted, whatever was asked for: a client that narrowed
// to a subset still needs to be told it missed some of that subset. Filtering it
// out would hide the one signal that says the log is incomplete.
func parseKindFilter(raw string) (kinds map[string]bool, unknown []string) {
	if strings.TrimSpace(raw) == "" {
		return nil, nil
	}
	valid := make(map[string]bool, len(store.AllKinds))
	for _, k := range store.AllKinds {
		valid[k] = true
	}
	kinds = map[string]bool{store.KindDropped: true}
	for _, k := range strings.Split(raw, ",") {
		if k = strings.TrimSpace(k); k == "" {
			continue
		}
		if !valid[k] {
			unknown = append(unknown, k)
			continue
		}
		kinds[k] = true
	}
	return kinds, unknown
}

// sseFrame renders one event as an SSE frame.
//
// EXTRACTED so it can be tested per kind. It was a closure inside the handler,
// which meant the only way to assert a kind serialises correctly was to drive a
// scenario that happens to emit it — so the tests covered the kinds someone
// wrote a scenario for, and a new kind was covered by nothing. Now a table test
// walks store.AllKinds and this function, and adding a kind grows it by itself.
//
// `event:` lets a browser client attach a listener per kind instead of switching
// on the payload — and it is why a kind missing from a client's subscription
// list never arrives at all: EventSource has no wildcard listener.
//
// `id:` lets EventSource resume, but ONLY for events carrying a sequence. A
// dropped notice is generated by this handler rather than the bus, and offering
// it as a resume point would tell a reconnecting client to skip past real
// events.
func sseFrame(ev store.Event) ([]byte, error) {
	body, err := json.Marshal(ev)
	if err != nil {
		return nil, err
	}
	head := fmt.Sprintf("event: %s\n", ev.Kind)
	if ev.Seq > 0 {
		head = fmt.Sprintf("id: %d\n%s", ev.Seq, head)
	}
	return fmt.Appendf(nil, "%sdata: %s\n\n", head, body), nil
}

func (s *Server) emulatorEvents(w http.ResponseWriter, r *http.Request) {
	flusher, ok := w.(http.Flusher)
	if !ok {
		writeJSON(w, http.StatusInternalServerError,
			map[string]any{"error": "streaming unsupported by this connection"})
		return
	}

	// ?kinds=table,activity — narrow the firehose. Absent means everything.
	kinds, unknown := parseKindFilter(r.URL.Query().Get("kinds"))
	if len(unknown) > 0 {
		// REFUSED, not ignored. An unrecognised name matches no event, so a
		// single typo — `?kinds=tabel` — used to yield a stream carrying only
		// dropped notices: an empty log, no error, and nothing to suggest the
		// filter was at fault rather than the platform. Naming the bad values
		// and the valid set turns a silent nothing into an answer.
		writeJSONError(w, http.StatusBadRequest, "UnknownEventKind",
			fmt.Sprintf("no such event kind(s): %s. Valid kinds: %s.",
				strings.Join(unknown, ", "), strings.Join(store.AllKinds, ", ")))
		return
	}

	// ?since=<seq> replays from the ring buffer, so a client that connects
	// mid-run still sees it. EventSource sets Last-Event-ID itself on
	// reconnect, which means a dropped connection resumes without a gap.
	since := int64(0)
	if v := r.URL.Query().Get("since"); v != "" {
		since, _ = strconv.ParseInt(v, 10, 64)
	}
	if v := r.Header.Get("Last-Event-ID"); v != "" {
		if n, err := strconv.ParseInt(v, 10, 64); err == nil {
			since = n
		}
	}

	w.Header().Set("Content-Type", "text/event-stream")
	w.Header().Set("Cache-Control", "no-cache")
	w.Header().Set("Connection", "keep-alive")
	// Without this an intermediary may buffer the whole response and the
	// stream never appears to start.
	w.Header().Set("X-Accel-Buffering", "no")
	w.WriteHeader(http.StatusOK)

	// Subscribe *before* replaying, so an event landing between the two is
	// queued rather than lost. Overlap is fine — the client de-duplicates on
	// seq, and replay is bounded.
	sub := s.Store.Subscribe()
	defer sub.Close()

	send := func(ev store.Event) bool {
		if kinds != nil && !kinds[ev.Kind] {
			return true
		}
		frame, err := sseFrame(ev)
		if err != nil {
			return true
		}
		if _, err := w.Write(frame); err != nil {
			return false
		}
		flusher.Flush()
		return true
	}

	var lastSent int64
	for _, ev := range s.Store.Replay(since) {
		if !send(ev) {
			return
		}
		lastSent = ev.Seq
	}

	every := s.EventKeepalive
	if every <= 0 {
		every = DefaultEventKeepalive
	}
	ticker := time.NewTicker(every)
	defer ticker.Stop()
	ctx := r.Context()

	// A gap must never pass silently. Checked on both branches below, so a
	// client that fell behind is told on the next event *or* the next
	// keepalive — the bus cannot tell it itself (see Subscription.TakeDropped).
	reportDrops := func() bool {
		n := sub.TakeDropped()
		if n == 0 {
			return true
		}
		return send(store.Event{Kind: store.KindDropped, At: s.Clock.Now(), Dropped: n})
	}

	for {
		select {
		case <-ctx.Done():
			return
		case ev := <-sub.C:
			if !reportDrops() {
				return
			}
			if ev.Seq <= lastSent {
				continue // already covered by the replay above
			}
			if !send(ev) {
				return
			}
			lastSent = ev.Seq
		case <-ticker.C:
			if !reportDrops() {
				return
			}
			// An SSE comment: keeps the connection warm, ignored by clients.
			if _, err := fmt.Fprint(w, ": keepalive\n\n"); err != nil {
				return
			}
			flusher.Flush()
		}
	}
}
