package server

// The SERVER half of the event contract.
//
// internal/store/bus_kinds_test.go proves AllKinds holds every declared
// constant, and the portal's tests prove the client subscribes to and renders
// every kind in the generated list. Neither says the wire format is right for
// each kind — and the scenario tests in events_test.go cannot: each drives a
// pipeline that happens to emit one or two kinds, so coverage followed whoever
// wrote a scenario. A new kind was asserted by nothing on this side.
//
// These walk store.AllKinds, so adding a kind grows them without anyone
// remembering to.

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/calvinchengx/fabric-emulator/internal/store"
)

// parseFrame splits one SSE frame into its fields. Deliberately literal: the
// point is to assert the bytes on the wire, not to re-implement a parser that
// agrees with the producer by construction.
func parseFrame(t *testing.T, raw []byte) (id, event, data string) {
	t.Helper()
	text := string(raw)
	if !strings.HasSuffix(text, "\n\n") {
		t.Fatalf("frame does not end in a blank line, so a client never sees it as complete: %q", text)
	}
	for _, line := range strings.Split(strings.TrimSuffix(text, "\n\n"), "\n") {
		field, value, ok := strings.Cut(line, ": ")
		if !ok {
			t.Fatalf("frame line %q is not `field: value`", line)
		}
		switch field {
		case "id":
			id = value
		case "event":
			event = value
		case "data":
			data = value
		default:
			t.Fatalf("unknown SSE field %q — a client ignores what it does not know, "+
				"so a typo here is silent", field)
		}
	}
	return id, event, data
}

// TestEverySSEFrameNamesItsKind.
//
// The `event:` name is load-bearing rather than decorative: EventSource has no
// wildcard listener, so a client attaches one listener per kind and a frame
// whose name it does not expect never arrives. A kind that serialised without
// its name, or under the wrong name, would be invisible in exactly the way a
// missing subscription is.
func TestEverySSEFrameNamesItsKind(t *testing.T) {
	for _, kind := range store.AllKinds {
		t.Run(kind, func(t *testing.T) {
			raw, err := sseFrame(store.Event{Seq: 7, At: 1700000000, Kind: kind, WorkspaceID: "ws-1"})
			if err != nil {
				t.Fatalf("kind %q does not serialise: %v", kind, err)
			}
			id, event, data := parseFrame(t, raw)

			if event != kind {
				t.Errorf("event name = %q, want %q — a client listening for %q "+
					"would never receive this", event, kind, kind)
			}
			// The payload must carry the kind too: the client switches on it to
			// render, and `dropped` is routed by it before any rendering.
			var back struct {
				Kind string `json:"kind"`
				Seq  int64  `json:"seq"`
			}
			if err := json.Unmarshal([]byte(data), &back); err != nil {
				t.Fatalf("data is not JSON a client can parse: %v (%q)", err, data)
			}
			if back.Kind != kind {
				t.Errorf("payload kind = %q, want %q — the name and the body must "+
					"agree or the two paths disagree about what arrived", back.Kind, kind)
			}
			if id != "7" {
				t.Errorf("id = %q, want \"7\" — without it EventSource cannot resume "+
					"from this event", id)
			}
		})
	}
}

// TestADroppedNoticeOffersNoResumePoint.
//
// A dropped notice is generated by the handler, not the bus, so it carries no
// sequence. Emitting `id:` for it would hand a reconnecting client a resume
// point that skips past real events — losing data while looking like recovery.
func TestADroppedNoticeOffersNoResumePoint(t *testing.T) {
	raw, err := sseFrame(store.Event{At: 1700000000, Kind: store.KindDropped, Dropped: 12})
	if err != nil {
		t.Fatal(err)
	}
	id, event, _ := parseFrame(t, raw)
	if event != store.KindDropped {
		t.Errorf("event name = %q, want %q", event, store.KindDropped)
	}
	if id != "" {
		t.Errorf("id = %q on a dropped notice; a client resuming from it would skip "+
			"every real event between there and now", id)
	}
}

// TestEveryKindIsAcceptedAsAFilter walks the contract: a client may narrow to
// any kind the bus carries, and none of them may be rejected as unknown.
//
// Driven off store.AllKinds so a new kind is covered without anyone adding a
// case — which is the whole point, since the failure mode is a name that looks
// valid and matches nothing.
func TestEveryKindIsAcceptedAsAFilter(t *testing.T) {
	for _, kind := range store.AllKinds {
		t.Run(kind, func(t *testing.T) {
			kinds, unknown := parseKindFilter(kind)
			if len(unknown) > 0 {
				t.Fatalf("kind %q rejected as unknown: %v", kind, unknown)
			}
			if !kinds[kind] {
				t.Errorf("a filter naming %q does not admit it", kind)
			}
			// Never filtered out, whatever was asked for: a narrowed client
			// still needs to know it missed some of its own subset.
			if !kinds[store.KindDropped] {
				t.Errorf("a filter for %q dropped the `dropped` notice — the one "+
					"signal that says the log is incomplete", kind)
			}
		})
	}
}

// TestAnUnknownKindIsRefusedRatherThanSilentlyMatchingNothing.
//
// The bug this closes: an unrecognised name matched no event, so `?kinds=tabel`
// produced a stream of nothing but dropped notices — an empty log, no error, and
// no reason to suspect the filter rather than the platform.
func TestAnUnknownKindIsRefusedRatherThanSilentlyMatchingNothing(t *testing.T) {
	_, unknown := parseKindFilter("tabel")
	if len(unknown) != 1 || unknown[0] != "tabel" {
		t.Fatalf("unknown = %v; a typo must be reported, not passed through", unknown)
	}
	// A valid name alongside a bad one is still an error: half-honouring the
	// filter would show a subset the caller never asked for.
	_, unknown = parseKindFilter("table,tabel")
	if len(unknown) != 1 || unknown[0] != "tabel" {
		t.Errorf("unknown = %v; want just the bad name", unknown)
	}
}

// TestAnAbsentFilterMeansEverything.
//
// `?kinds=` must not mean "nothing". A nil set is how the handler says "no
// filter", and returning an empty non-nil map instead would give a client that
// passed an empty parameter a permanently dead stream.
func TestAnAbsentFilterMeansEverything(t *testing.T) {
	for _, raw := range []string{"", "   ", ","} {
		kinds, unknown := parseKindFilter(raw)
		if len(unknown) > 0 {
			t.Errorf("parseKindFilter(%q) reported unknown %v", raw, unknown)
		}
		if raw == "," {
			// A lone separator names no kind: the set exists but admits only the
			// dropped notice. Documented rather than silently treated as "all".
			continue
		}
		if kinds != nil {
			t.Errorf("parseKindFilter(%q) = %v; want nil, which the handler reads "+
				"as everything", raw, kinds)
		}
	}
	// Whitespace around a real name is tolerated — a hand-typed curl query.
	kinds, _ := parseKindFilter(" table , job ")
	if !kinds["table"] || !kinds["job"] {
		t.Errorf("whitespace-padded names were not honoured: %v", kinds)
	}
}
