#!/usr/bin/env python3
"""Run the capability probes against both Spark engines and generate the matrix.

Output is `docs/engine-matrix.md` — generated, not hand-written, because the
hand-written version drifted: a row claimed streaming failed on Sail long after
Sail gained streaming support, and three capabilities were bundled under one
verdict that hid a partial pass.

    ./run.py            run both engines and rewrite the matrix
    ./run.py --engine sail   run one engine only (leaves the other's results)
    ./run.py --check    fail if the generated matrix differs from the committed
                        one (CI mode: the matrix must be regenerated when the
                        engines change)
"""
import argparse
import json
import os
import pathlib
import subprocess
import sys

DIR = pathlib.Path(__file__).resolve().parent
OUT = DIR / "out"
MATRIX = DIR.parent.parent / "docs" / "engine-matrix.md"
COMPOSE = ["docker", "compose", "-f", str(DIR / "docker-compose.yml")]
ENGINES = ("sail", "sail-delta", "jvm")


def ensure_out_writable() -> None:
    """Make `out/` writable by whatever uid the probe containers run as.

    The JVM image is `apache/spark`, which drops to `USER spark` (uid 185). The
    bind-mounted `out/` is owned by the checkout user, so that probe ran every
    capability and then died on `PermissionError: '/out/jvm.json'` — after the
    measuring was done, which is the most wasteful place to fail.

    It passed on macOS throughout: Docker Desktop's filesystem ignores the uid
    mismatch, so only Linux CI ever saw it. That is why this job had never gone
    green despite the matrix regenerating cleanly on a laptop every time.

    The existing result files need chmod too, not just the directory. The
    directory bits govern create/delete/rename; `open(path, "w")` *truncates*
    an existing file, which needs write permission on that file. Since
    `out/*.json` are tracked, checkout recreates them 644 and owned by the
    runner, so a writable directory alone changes nothing — which is exactly
    how the first attempt at this fix failed.
    """
    OUT.mkdir(parents=True, exist_ok=True)
    os.chmod(OUT, 0o777)
    for existing in OUT.glob("*.json"):
        os.chmod(existing, 0o666)


def run_engine(engine: str) -> int:
    service = {"sail": "sail-probe", "sail-delta": "sail-delta-probe"}.get(engine, "jvm-probe")
    print(f"==> probing {engine}", flush=True)
    try:
        result = subprocess.run(
            COMPOSE + ["--profile", engine, "up", "--build",
                       "--abort-on-container-exit", "--exit-code-from", service])
        return result.returncode
    finally:
        subprocess.run(COMPOSE + ["--profile", engine, "down", "-v"],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def load(engine: str):
    path = OUT / f"{engine}.json"
    if not path.exists():
        raise SystemExit(f"no results for {engine}: {path} missing")
    return {r["id"]: r for r in json.loads(path.read_text())}


def cell(result) -> str:
    if result is None:
        return "—"
    if result["status"] == "pass":
        return "✅"
    err = result.get("error", "")
    # The message is the useful part: it says *why*, and different messages
    # point at different upstream fixes.
    return f"❌ `{err[:90]}`" if err else "❌"


def render() -> str:
    sail, jvm = load("sail"), load("jvm")
    sail_delta = load("sail-delta")
    order = [r["id"] for r in json.loads((OUT / "jvm.json").read_text())]
    lines = [
        "# Spark engine matrix — Sail vs JVM",
        "",
        "**Generated by `e2e/engine-matrix/run.py`. Do not edit by hand.**",
        "",
        "The same probe runs against both engines. A capability is never bundled",
        "with another: each row is one probe, and a failure records the engine's",
        "own error message, because `No table format found for: memory` and",
        "`unsupported extension node for streaming: DeltaWriteNode` are different",
        "facts pointing at different fixes.",
        "",
        "Rows where the engines differ are the honest content of the",
        "🔴 default / 🟠 JVM overlay marks in [parity.md](parity.md).",
        "",
        "Three columns, because *engine* and *emulator* are different things:",
        "**Sail (engine)** is the bare engine; **Sail + delta-rs** is what a user",
        "actually gets, since the Livy agent installs the delta-rs interception",
        "for every Sail session ([20-lakesail-engine.md](20-lakesail-engine.md)).",
        "The middle column runs the agent's own module, not a re-implementation,",
        "so it cannot drift from the runtime it describes.",
        "",
        "## The JVM column is OSS Spark, not Fabric's Spark",
        "",
        "**This matrix has no Fabric in it.** The JVM column is upstream",
        "Apache Spark; Fabric ships a Microsoft distribution with its own",
        "runtime additions, and nothing here has ever been compared against",
        "it. So a row where Sail matches JVM says *matches open-source",
        "Spark* — a weaker statement than this table's placement beside",
        "the parity map suggests.",
        "",
        "The probe count is also a thin slice of what a real notebook",
        "touches. It grew from remembered gaps rather than from measured",
        "usage, so a capability nobody here thought to probe is absent",
        "rather than red — the same denominator problem",
        "[parity.md](parity.md) states for its own rows.",
        "",
        "The only oracle that could settle either point is",
        "`.github/workflows/real-fabric.yml`, against a tenant.",
        "",
        "## How to read a cell",
        "",
        "A ✅ means *this probe passed on this engine* — nothing wider. A ❌ is",
        "not a verdict that the capability is impossible; it is the engine's own",
        "error, kept verbatim because the message is the actionable part. Three",
        "distinct things hide behind ❌, and the footnotes say which is which:",
        "",
        "1. **A real gap** — the engine cannot do it (`sc` / `_jvm` on Connect;",
        "   checkpointed streaming on Sail; bare Sail has no kafka source).",
        "2. **A protocol limit** — Spark Connect itself forbids it (`sc`, `_jvm`),",
        "   so no upstream fix exists for *any* Connect client, Sail or Apache's.",
        "3. **A harness artefact** — the probe's environment, not the engine.",
        "   These are bugs in the table and get fixed rather than explained away:",
        "   the Python UDF row was one, until the pyspark client pin was corrected",
        "   to the version pysail is built against.",
        "",
        "Read a ❌ next to a ✅ in the same row as \"the emulator closes this gap\",",
        "and two ❌ with *different* messages as two different problems.",
        "",
        "## How the table is produced",
        "",
        "Four rules, each of them a reaction to a way an earlier hand-written",
        "version misled:",
        "",
        "- **Generated, never edited.** A hand-written row claimed streaming was",
        "  broken on Sail long after Sail gained streaming. Prose drifts from",
        "  reality silently; a generated file cannot. CI regenerates and diffs.",
        "- **One probe per capability, never bundled.** Three capabilities once",
        "  shared one verdict, which hid a partial pass. A row that covers two",
        "  things can only report the worse of them.",
        "- **The error text is recorded, not summarised.** `No table format found",
        "  for: memory` and `unsupported extension node for streaming:",
        "  DeltaWriteNode` point at different upstream fixes; \"streaming sink",
        "  fails\" points at neither.",
        "- **The middle column imports the shipped module.** It does not",
        "  re-implement the interception. If the agent changes, the column moves",
        "  with it — the table cannot claim a behaviour the runtime lacks.",
        "",
        "What this table does **not** do: prove the OneLake path. The probes run",
        "against local table paths, so credentials are out of scope here and are",
        "witnessed separately by `e2e/livy` against `abfss://…onelake…`, with a",
        "negative control (a deliberately wrong bearer must be refused). Keeping",
        "those separate is deliberate — a capability probe that also needed",
        "storage auth would fail for two unrelated reasons and distinguish",
        "neither.",
        "",
        "## Which engine should I use?",
        "",
        "**Sail is the default, and should stay the default.** This table only",
        "measures capability; it says nothing about the axis Sail was chosen for.",
        f"Measured on the same {len(order)} probes:",
        "",
        "| | Sail | Spark JVM |",
        "|---|---|---|",
        "| Image size | **943 MB** | **2.1 GB** |",
        "| Run output | 125 log lines | **78,040 log lines** |",
        "| Wall clock | seconds | minutes |",
        "",
        "And the differences are fewer than the row count suggests:",
        "",
        "* two (`sc`, `spark._jvm`) are **Spark Connect protocol** limits, not Sail",
        "  choices — Apache Spark's own Connect client cannot expose them either,",
        "  so no upstream fix exists;",
        "* one (`MERGE` at a local path) works on `az://`, the path the emulator",
        "  actually uses.",
        "",
        "The common notebook path — Delta write/append, both time-travel forms,",
        "`createDataFrame`, SQL, `readStream` — passes on **both**. Ordinary work",
        "sees no difference except speed.",
        "",
        "**Reach for the JVM overlay when your test touches** Java/Scala UDFs /",
        "`spark.jars`, the RDD/`_jvm` surface, or a **checkpointed** streaming",
        "query (`foreachBatch` on an engine stream). Those are the ❌ rows that",
        "stay red in the middle column. Durable streaming *sinks* (delta /",
        "parquet / memory) land one announced micro-batch there — not a Fabric-",
        "shaped checkpointed query. OSS `format(\"kafka\")` (source and sink) is",
        "the same class of wrap (driver consume/produce → Sail LocalRelation).",
        "`OPTIMIZE`/`VACUUM`, LOCATION-bearing",
        "`CREATE TABLE`, MERGE, DESCRIBE, Change Data Feed, JSON `multiLine`,",
        "and those sinks are closed on the Livy path.",
        "One flag:",
        "",
        "```bash",
        "docker compose -f docker-compose.yml -f docker-compose.override.yml \\",
        "               -f docker-compose.spark-jvm.yml up",
        "```",
        "",
        "Real Fabric Runtime 1.3 *is* JVM Spark 3.5.5 + Delta 3.2 + Java 11, so",
        "the overlay is the higher-fidelity engine. It is not the default because",
        "a 2.1 GB image and a minutes-long startup would cost every user speed to",
        "buy capabilities most tests never touch.",
        "",
        "| Capability | Sail (engine) | Sail + delta-rs (emulator) | Spark JVM |",
        "|---|---|---|---|",
    ]
    differing = 0
    for probe_id in order:
        s, sd, j = sail.get(probe_id), sail_delta.get(probe_id), jvm.get(probe_id)
        desc = (j or s or {}).get("description", probe_id)
        # "Differs" is measured against what the emulator actually delivers —
        # the middle column — not the bare engine.
        if sd and j and sd["status"] != j["status"]:
            differing += 1
        lines.append(f"| {desc} | {cell(s)} | {cell(sd)} | {cell(j)} |")
    lines += [
        "",
        f"**{differing} of {len(order)} capabilities differ between the engines.**",
        "Those are precisely the rows the JVM overlay exists for, and the",
        "candidate list for upstream Sail contributions.",
        "",
        "ᵃ Qualified deliberately. `e2e/sail` proves the same `MERGE` succeeds on",
        "Sail when the registered table is backed by an `az://` OneLake URL — the",
        "path the emulator actually uses. Only the local-path form fails on the",
        "bare engine, so the Sail column is not evidence that Sail lacks `MERGE`.",
        "",
        "The middle column intercepts this probe shape: a subquery source and",
        "`INSERT *`, the same split CTAS uses (SELECT on the engine, upsert",
        "through delta-rs). Named-source MERGE (the medallion shape) was already",
        "intercepted. `WHEN MATCHED THEN DELETE` still falls through.",
        "",
        "ᶜ These two assert less than the others, and say so rather than",
        "implying more. Every other streaming row now proves rows actually",
        "**reached the sink** — files read back, or a queryable table — after a",
        "green `console` cell was found to mean only that a query object",
        "reported itself active while the engine delivered nothing. No stronger",
        "assertion exists from a Spark Connect client for these two: `console`",
        "writes to the *server's* stdout, a `readStream` is unobservable without",
        "a sink, and Sail reports no progress metrics (`lastProgress` is None,",
        "`recentProgress` is empty) — so asserting on those would fail for a",
        "missing API rather than a missing capability.",
        "",
        "ⁱ The three durable sink rows (memory / parquet / delta) on the",
        "**middle column** wrap `writeStream.start()`: Sail's streaming `rate`",
        "plan is collected as a bounded query (`limit(n).collect()`, measured",
        "2026-08-14) and the rows are batch-written (or registered as a temp",
        "view). Announced on stderr. There is no checkpoint; a continuous query",
        "lands one micro-batch. Bare Sail still fails with `DeltaWriteNode` /",
        "`listing table` / `No table format found for: memory`. `foreachBatch`",
        "on an engine stream falls through. Native `format(\"kafka\")` (source",
        "and sink) is ʲ. Native checkpointed streaming is the JVM overlay.",
        "",
        "ᵇ The CDF row on the **middle column** intercepts both halves of the",
        "notebook API: a Delta write with `delta.enableChangeDataFeed` (and later",
        "appends to that table) and a read with `readChangeFeed`, announced on",
        "stderr. The result is materialised (`createDataFrame`); `.explain()` is",
        "a LocalRelation. Bare Sail still cannot enable the table feature",
        "(`Unsupported table features required: [ChangeDataFeed]`), and",
        "`e2e/sail` — which does not install this interception — still shows the",
        "unwrapped `readChangeFeed` option as accepted and inert. The helper",
        "`spark.delta_change_feed` remains, verified in `e2e/livy` against",
        "OneLake. Native CDF on a classic session is the JVM overlay.",
        "",
        "ᵈ This row is green, and it is here to keep it that way — it records a",
        "capability we briefly believed was MISSING. The dbt-fabricspark medallion",
        "models failed with `attribute ObjectName([Identifier(\"_rn\")]) is missing",
        "from the schema: cannot resolve attribute` and were rewritten into two",
        "CTEs, with the cause attributed to Sail. This probe is that exact shape —",
        "rank into `_rn`, keep `_rn = 1`, project only the real columns — and Sail",
        "executes it correctly over Spark Connect. So does a plain unprojected",
        "filter, and so does the view-materialised form.",
        "",
        "The attribution was therefore wrong, or at least unproven: whatever",
        "rejected `_rn` lives on the **Livy path** (emulator to spark-agent to",
        "Sail) or in dbt's generated SQL, not in Sail's SQL support. Not yet",
        "localised further — dbt projects an explicit column list over a wide",
        "Delta source, which this probe does not reproduce at that width. The",
        "two-CTE rewrite is portable and costs nothing, so it should stay; what",
        "should not stay is the belief that Sail cannot do this.",
        "",
        "ᵉ The real cause of the `_rn` failure ᵈ was chasing. Sail answers",
        "`DESCRIBE TABLE` on a catalog-registered Delta table with the correct",
        "SCHEMA and ZERO ROWS, and raises nothing. Against a temp view it answers",
        "correctly, so the gap is specific to registered tables — which is exactly",
        "what the emulator's `registerLakehouseTables` creates for every lakehouse",
        "table, so it reaches any consumer that introspects, not just dbt.",
        "",
        "It stayed invisible because every component behaved reasonably. Sail",
        "returns no rows and no error; the Livy agent forwards that faithfully",
        "(the schema has three fields, so it is not an empty envelope); dbt's",
        "`get_columns_in_relation` reads it as \"this table has no columns\"; the",
        "model's Jinja loops over an empty list and emits nothing; the compiled",
        "SQL becomes `select` followed by `from`. Nobody lied — the information",
        "that the answer was MISSING did not survive the chain. A consumer cannot",
        "tell \"no columns\" from \"the engine did not answer\", and that",
        "indistinguishability is the actual defect.",
        "",
        "The medallion models now read columns from",
        "`run_query(\"select * from t limit 0\").column_names`, which carries the",
        "schema in the result envelope and never asks the catalog. This row going",
        "green on the **middle column** is the emulator answering from the Delta",
        "log once the table's LOCATION is recorded (`registerLakehouseTables`, or",
        "`CREATE TABLE … USING delta LOCATION` passing through `spark.sql`). The",
        "Sail column stays the zero-row gap; that is still what a bare engine",
        "returns. A name nobody recorded still falls through to Sail.",
        "",
        "\u1d4d Delta-by-default is a FABRIC property. Bare Sail and the JVM overlay",
        "both default to Hive, so a `CREATE TABLE … LOCATION` with no `USING`",
        "does not write Delta on either engine. The **middle column** honours an",
        "explicit LOCATION and writes Delta — more faithful to Fabric than the",
        "JVM overlay, which is why this row can be ❌ / ✅ / ❌.",
        "",
        "dbt-fabricspark's file_format_clause macro emits NO clause for exactly",
        "one value of file_format: `delta`, the one the adapter assumes is the",
        "default. So a model configured `+file_format: delta` with `+location_root`",
        "pointing at the lakehouse emitted `create or replace table ... location",
        "'...' as ...` with no USING, and the lakehouse never received silver",
        "while dbt reported success. Two rounds of debugging went into a config",
        "that was being applied correctly the whole time: the same value that",
        "proved it was applied was the value that suppressed the clause.",
        "",
        "The fabricspark__file_format_clause override in the examples is still",
        "required on **bare OSS Spark**, including the JVM overlay. It is not a",
        "Sail workaround waiting for a better engine — it is the price of running",
        "dbt-fabricspark anywhere that is not Fabric (or this emulator's",
        "LOCATION interception). That is worth knowing before someone deletes it",
        "as Sail-specific.",
        "",
        "ᶠ The same question asked of the OTHER introspection route. On bare Sail",
        "it fails the opposite way from ᵉ: `DETAIL` is not in the DESCRIBE grammar",
        "at all, so this RAISES rather than returning nothing. That is the better",
        "failure — a `collect()[0]` never runs on an empty list; instead it gets a",
        "parse error naming the statement.",
        "",
        "The middle column answers from the Delta log once the table's LOCATION is",
        "recorded, the same way ᵉ does. Named `OPTIMIZE`/`VACUUM` use that cache",
        "(`remember()`), not a round-trip through Sail's missing grammar. A name",
        "nobody recorded still falls back to `DESCRIBE DETAIL` and fails loudly.",
        "",
        "Kept as its own row rather than folded into ᵉ because the contrast is the",
        "lesson: the silent one cost a day, the loud one cost minutes, and they",
        "are the same missing capability on the bare engine.",
        "",
        "\u02b0 These two arrived as a report that Sail ACCEPTS AND IGNORES both",
        "options. Measuring it found one real gap and one false alarm, and the",
        "false alarm is the more useful half.",
        "",
        "`multiLine` on the **middle column** wraps `DataFrameReader.json` for the",
        "named option only, parses the file on the driver (including a Spark",
        "text-writer directory: part file in, `_SUCCESS` skipped), and materialises",
        "via `createDataFrame`. Announced on stderr; `.explain()` is a LocalRelation.",
        "Plain `json()`, `multiLine=False`, a list of paths, and a schema fall",
        "through. Bare Sail stays NDJSON-only: a file that is one JSON array cannot",
        "be parsed at all, while Spark JVM reads it natively. The exact message",
        "depends on the fixture's shape, so read the Sail-column cell as evidence of",
        "NDJSON-only parsing rather than as a fixed string — the array here spans",
        "lines, so the reader fails on a bare `[`; an array on ONE line fails",
        "differently (`Expected JSON record to be an object, found Array`).",
        "The multi-line fixture is kept because it exercises both halves of the",
        "option: spanning lines AND being an array.",
        "",
        "`wholetext` is GREEN on Sail, and this row exists to keep it that way —",
        "like \u1d48, it records a capability we were told was missing and is not.",
        "The reported symptom (one row per LINE, on both engines) reproduces",
        "exactly, but it is a PySpark spelling artifact rather than an engine",
        "limit: `DataFrameReader.text(path, wholetext=False, ...)` passes that",
        "DEFAULT into `_set_opts`, which overwrites any `.option(\"wholetext\", ...)`",
        "set beforehand. So the `.option()` form cannot take effect for this",
        "reader on ANY engine. Measured on one JVM session against one file:",
        "`.option()` -> 3 rows, `text(p, wholetext=True)` -> 1 row. Both probes",
        "therefore use the keyword form.",
        "",
        "That is why the JVM column is worth reading first. A probe written the",
        "`.option()` way turns every engine red, including the reference one, and",
        "a red reference cell is the tell that the probe is measuring itself. The",
        "companion trap is the fixture: with ONE line per file, honoured and",
        "ignored give an identical row count, which is how the original report",
        "first concluded `wholetext` WORKED. Both probes therefore use a",
        "multi-line fixture and assert the PLAIN read first, so a broken fixture",
        "reports itself as a broken fixture rather than as a missing capability —",
        "the same discipline as the streaming rows \u1d9c, which assert rows reached",
        "the sink rather than that a query started.",
        "",
        "The fixtures are written through the ENGINE, not with a client-side",
        "open(): on the `sail` profile the probe runs in a different container",
        "and shares no volume with the engine, so a client-written file would not",
        "be there to read.",
        "",
        "Reported from contoso-data-platform, where the `multiLine` workaround is",
        "to read the page as text and parse in-engine (`from_json` + `explode`),",
        "keeping the data path distributed. That has its own trap: `from_json`",
        "returns NULL on a schema mismatch rather than raising, and the row count",
        "comes from the array's length rather than its contents, so every",
        "count-based assertion still passes while every column is empty.",
        "",
        "\u02b2 OSS `spark.read.format(\"kafka\")` with `kafka.bootstrap.servers` +",
        "`subscribe` (the measured probe). The **middle column** consumes on the",
        "driver (kafka-python) and `createDataFrame`s the Kafka schema",
        "(`key`/`value`/`topic`/`partition`/`offset`) into Sail; `CAST(value AS",
        "STRING)` therefore runs on the engine. Announced; one micro-batch;",
        "`.explain()` is a LocalRelation. Not `rate`. The same wrap honours",
        "`subscribePattern`, `assign`, JSON `startingOffsets`/`endingOffsets`,",
        "`includeHeaders`, SASL PLAIN, GSSAPI, PEM SSL, JKS/P12 truststores, and",
        "a kafka *sink* (`write`/`writeStream.format(\"kafka\")`) — unit-tested,",
        "not this probe. Bare Sail has no kafka source. JVM uses `spark-sql-kafka`.",
        "Checkpointed streaming stays on the overlay.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--engine", choices=ENGINES)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not args.check:
        ensure_out_writable()
        for engine in ([args.engine] if args.engine else ENGINES):
            code = run_engine(engine)
            if code != 0:
                print(f"probe run for {engine} exited {code}", file=sys.stderr)
                return code

    generated = render()
    if args.check:
        current = MATRIX.read_text() if MATRIX.exists() else ""
        if current != generated:
            print("docs/engine-matrix.md is out of date — regenerate with "
                  "e2e/engine-matrix/run.py", file=sys.stderr)
            return 1
        print("engine matrix is current")
        return 0
    MATRIX.write_text(generated)
    print(f"wrote {MATRIX}")
    print(generated)
    return 0


if __name__ == "__main__":
    sys.exit(main())
