#!/usr/bin/env python3
"""Run the capability probes against both Spark engines and generate the matrix.

Output is `docs/engine-matrix.md` — generated, not hand-written, because the
hand-written version drifted: a row claimed streaming failed on Sail long after
Sail gained streaming support, and three capabilities were bundled under one
verdict that hid a partial pass.

    ./run.py            run both engines and rewrite the matrix
    ./run.py --engine sail   run one engine only (leaves the other's results)
    ./run.py --check    fail if the generated matrix differs from the committed
                        one (CI mode: the matrix must be regenerated when the
                        engines change)
"""
import argparse
import json
import os
import pathlib
import subprocess
import sys

DIR = pathlib.Path(__file__).resolve().parent
OUT = DIR / "out"
MATRIX = DIR.parent.parent / "docs" / "engine-matrix.md"
COMPOSE = ["docker", "compose", "-f", str(DIR / "docker-compose.yml")]
ENGINES = ("sail", "jvm")


def run_engine(engine: str) -> int:
    service = "sail-probe" if engine == "sail" else "jvm-probe"
    print(f"==> probing {engine}", flush=True)
    try:
        result = subprocess.run(
            COMPOSE + ["--profile", engine, "up", "--build",
                       "--abort-on-container-exit", "--exit-code-from", service])
        return result.returncode
    finally:
        subprocess.run(COMPOSE + ["--profile", engine, "down", "-v"],
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


def load(engine: str):
    path = OUT / f"{engine}.json"
    if not path.exists():
        raise SystemExit(f"no results for {engine}: {path} missing")
    return {r["id"]: r for r in json.loads(path.read_text())}


def cell(result) -> str:
    if result is None:
        return "—"
    if result["status"] == "pass":
        return "✅"
    err = result.get("error", "")
    # The message is the useful part: it says *why*, and different messages
    # point at different upstream fixes.
    return f"❌ `{err[:90]}`" if err else "❌"


def render() -> str:
    sail, jvm = load("sail"), load("jvm")
    order = [r["id"] for r in json.loads((OUT / "jvm.json").read_text())]
    lines = [
        "# Spark engine matrix — Sail vs JVM",
        "",
        "**Generated by `e2e/engine-matrix/run.py`. Do not edit by hand.**",
        "",
        "The same probe runs against both engines. A capability is never bundled",
        "with another: each row is one probe, and a failure records the engine's",
        "own error message, because `No table format found for: memory` and",
        "`unsupported extension node for streaming: DeltaWriteNode` are different",
        "facts pointing at different fixes.",
        "",
        "Rows where the engines differ are the honest content of the",
        "🔴 default / 🟠 JVM overlay marks in [parity.md](parity.md).",
        "",
        "| Capability | Sail | Spark JVM |",
        "|---|---|---|",
    ]
    differing = 0
    for probe_id in order:
        s, j = sail.get(probe_id), jvm.get(probe_id)
        desc = (j or s or {}).get("description", probe_id)
        if s and j and s["status"] != j["status"]:
            differing += 1
        lines.append(f"| {desc} | {cell(s)} | {cell(j)} |")
    lines += [
        "",
        f"**{differing} of {len(order)} capabilities differ between the engines.**",
        "Those are precisely the rows the JVM overlay exists for, and the",
        "candidate list for upstream Sail contributions.",
        "",
        "ᵃ Qualified deliberately. `e2e/sail` proves the same `MERGE` succeeds on",
        "Sail when the registered table is backed by an `az://` OneLake URL — the",
        "path the emulator actually uses. Only the local-path form fails, so this",
        "row is not evidence that Sail lacks `MERGE`.",
        "",
        "ᵇ A failure here is a pyspark client/worker protocol mismatch in the probe",
        "container, not a missing capability: Sail embeds CPython via `pyo3` to run",
        "Python UDFs. Fix by pinning matching pyspark versions.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--engine", choices=ENGINES)
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    if not args.check:
        for engine in ([args.engine] if args.engine else ENGINES):
            code = run_engine(engine)
            if code != 0:
                print(f"probe run for {engine} exited {code}", file=sys.stderr)
                return code

    generated = render()
    if args.check:
        current = MATRIX.read_text() if MATRIX.exists() else ""
        if current != generated:
            print("docs/engine-matrix.md is out of date — regenerate with "
                  "e2e/engine-matrix/run.py", file=sys.stderr)
            return 1
        print("engine matrix is current")
        return 0
    MATRIX.write_text(generated)
    print(f"wrote {MATRIX}")
    print(generated)
    return 0


if __name__ == "__main__":
    sys.exit(main())
