// GENERATED by scripts/gen_event_kinds.py from internal/store/bus.go.
// Do not edit: `make check` fails when this file and the Go declarations
// disagree. Change them there and regenerate.
//
// The SSE stream names every frame (`event: <kind>`) and EventSource has no
// wildcard listener, so a kind missing from EVENT_KINDS is not merely
// unfiltered — it never arrives at all. The types go further: a `switch`
// over EventKind that forgets a kind, or a field renamed in Go, is a compile
// error rather than a blank on screen.

/** Every kind the bus can carry. Subscribe to all of them. */
export const EVENT_KINDS = [
  'file',
  'table',
  'job',
  'activity',
  'lineage',
  'query',
  'dropped',
] as const;

/** The kinds a user may filter: things that happened to the PLATFORM.
 *
 * `dropped` is deliberately absent — it reports that THIS browser fell
 * behind, so hiding it would hide that the log is incomplete.
 */
export const VIEW_KINDS = [
  'file',
  'table',
  'job',
  'activity',
  'lineage',
  'query',
] as const;

/** Every kind, as a type: `switch (ev.kind)` is exhaustive against this. */
export type EventKind = (typeof EVENT_KINDS)[number];

/** The filterable kinds, as a type. */
export type ViewKind = (typeof VIEW_KINDS)[number];

/** What each kind means, for tooltips and for anyone reading this file. */
export const KIND_DOC: Record<EventKind, string> = {
  'file': 'a OneLake path was written, renamed, or deleted',
  'table': 'a Delta commit landed: a table has a new version',
  'job': 'an item job started or reached a terminal state',
  'activity': 'a pipeline activity reached its outcome',
  'lineage': 'a source→target movement was recorded',
  'query': 'a semantic model was queried (the Power BI hop)',
  'dropped': 'a subscriber fell behind; N events were lost',
};

/** Narrows an arriving `kind` to one this build knows.
 *
 * The portal ships inside its own emulator so it cannot be out of step with
 * its server, but `/_emulator/events` is a stream anything may read and
 * anything may point at a different build — so a parsed frame is treated as
 * untrusted rather than assumed to match these types.
 */
export function isEventKind(kind: string): kind is EventKind {
  return (EVENT_KINDS as readonly string[]).includes(kind);
}

/** Is this a kind the log renders? See VIEW_KINDS. */
export function isViewKind(kind: string): kind is ViewKind {
  return (VIEW_KINDS as readonly string[]).includes(kind);
}

/** Which unit of work moved some bytes. Never inferred: an engine reports
 * it, or the emulator's own executor knows it because it did the write.
 */
export interface Attribution {
  jobId?: string;
  activityName?: string;
  // CellIndex is a pointer because cell 0 is a real cell: a plain int could
  // not tell "the first cell" from "no cell at all".
  cellIndex?: number;
}

/** One event, in the flat envelope the SSE endpoint serialises.
 *
 * `store.Event` in Go; renamed here because `Event` is a DOM global and an
 * interface of that name would shadow the type DOM event handlers are
 * checked against.
 *
 * Fields are per-kind and absent when they do not apply, so this is every
 * kind's shape in one interface rather than a discriminated union: the
 * server emits one struct and this mirrors it exactly.
 */
export interface EmulatorEvent {
  seq: number;
  at: number; // emulator time, like every other timestamp here
  kind: EventKind;

  workspaceId?: string;
  itemId?: string;

  // KindFile
  eventType?: string;
  path?: string;

  // KindTable. Version is a pointer so that a table's *first* commit —
  // version 0, the common case for a fresh medallion — is still reported,
  // while file events do not carry a meaningless "version": 0.
  table?: string;
  version?: number;
  rowsAdded?: number;
  filesAdded?: number;
  filesRemoved?: number;

  // KindJob. Field NAMES match the job-instance wire shape, so a consumer
  // reading the stream and a consumer polling the API use the same keys.
  //
  // The STATUS VALUES do not fully match, and the difference is deliberate:
  // this is an event log, the API reports a state. A job that begins emits
  // `Started` here, which StatusAt never returns — polling the same job shows
  // `InProgress`. Both are right for what they describe, and a consumer that
  // treats the stream's vocabulary as the API's enum will classify every job
  // start as an unknown status. One did.
  jobId?: string;
  jobType?: string;
  invokeType?: string;
  status?: string;
  failureReason?: string;

  // KindActivity — pipeline.ActivityRun's fields, under its own JSON names.
  activityName?: string;
  activityType?: string;
  error?: string;
  durationInSeconds?: number;
  retryAttempt?: number;

  // KindLineage — a movement was recorded, so a graph can redraw without
  // waiting for a job to end. The edge itself stays in lineage_edges; this
  // carries just enough to describe the hop in a log line.
  sourceItemId?: string;
  sourcePath?: string;
  // SourceKind is set on a lineage event whose source is not a Fabric item.
  // Without it a consumer renders an empty sourcePath — a source system has
  // none — and shows "undefined" where the vendor's name belongs.
  sourceKind?: string;
  targetPath?: string;
  producer?: string;

  // KindQuery — a read, not a movement, so it is an event and never an edge.
  dataset?: string;
  queries?: number;

  // KindDropped
  dropped?: number;

  // Who caused this, when that is known — see Attribution.
  attribution?: Attribution;
}

/** An event as it ARRIVES, before its kind has been checked. */
export type RawEmulatorEvent = Omit<EmulatorEvent, 'kind'> & { kind: string };
