// GENERATED by scripts/gen_event_kinds.py from internal/store/bus.go.
// Do not edit: `make check` fails when this file and the Go constants
// disagree. Add a kind there and regenerate.
//
// The SSE stream names every frame (`event: <kind>`) and EventSource has no
// wildcard listener, so a kind missing from EVENT_KINDS is not merely
// unfiltered — it never arrives at all.

/** Every kind the bus can carry. Subscribe to all of them. */
export const EVENT_KINDS = [
  'file',
  'table',
  'job',
  'activity',
  'lineage',
  'query',
  'dropped',
];

/** The kinds a user may filter: things that happened to the PLATFORM.
 *
 * `dropped` is deliberately absent — it reports that THIS browser fell
 * behind, so hiding it would hide that the log is incomplete.
 */
export const VIEW_KINDS = [
  'file',
  'table',
  'job',
  'activity',
  'lineage',
  'query',
];

/** What each kind means, for tooltips and for anyone reading this file. */
export const KIND_DOC = {
  'file': 'a OneLake path was written, renamed, or deleted',
  'table': 'a Delta commit landed: a table has a new version',
  'job': 'an item job started or reached a terminal state',
  'activity': 'a pipeline activity reached its outcome',
  'lineage': 'a source→target movement was recorded',
  'query': 'a semantic model was queried (the Power BI hop)',
  'dropped': 'a subscriber fell behind; N events were lost',
};
