#!/usr/bin/env python3
"""Generate the portal's event-kind list from internal/store/bus.go.

WHY GENERATE RATHER THAN SERVE. The SSE stream names every frame
(`event: <kind>`), and EventSource has no wildcard listener — so a kind absent
from the client's subscription list is INVISIBLE. No error, no dropped count,
no event. The portal carried that list as a literal in three places, and nothing
checked them against the Go constants.

An endpoint the client fetches at runtime would also work, and would be the
right answer if the client could be older than the server. It cannot:
portal/embed.go embeds portal/dist into the binary, so the portal and the
emulator are the same artifact and always ship together. Generating therefore
makes drift IMPOSSIBLE rather than detected, with no endpoint, no round trip and
no fallback path to get wrong.

The labels come from each constant's trailing comment, so the one place a kind
is described is the one place it is declared.

Usage:
    gen_event_kinds.py            rewrite portal/src/eventKinds.js
    gen_event_kinds.py --check    exit non-zero if it is out of date
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
BUS = ROOT / "internal" / "store" / "bus.go"
OUT = ROOT / "portal" / "src" / "eventKinds.js"

# `KindFile     = "file"     // a OneLake path was written, renamed, or deleted`
CONST = re.compile(r'^\s+Kind(\w+)\s+=\s+"([a-z]+)"\s*//\s*(.+?)\s*$', re.M)
# `var ViewKinds = []string{ … }` — the slice bodies, so the split between a
# platform event and the subscriber signal is Go's decision, not this script's.
SLICE = r"var\s+%s\s*=\s*\[\]string\{(.*?)\}"


def slice_members(src: str, name: str) -> list[str]:
    m = re.search(SLICE % name, src, re.S)
    if not m:
        sys.exit(f"gen_event_kinds: no `var {name} = []string{{…}}` in {BUS.name}")
    return re.findall(r"Kind(\w+)", m.group(1))


def render() -> str:
    src = BUS.read_text(encoding="utf-8")
    consts = {name: (value, doc) for name, value, doc in CONST.findall(src)}
    if not consts:
        sys.exit(f"gen_event_kinds: no Kind… constants found in {BUS.name} — "
                 f"this generator is reading the wrong thing")

    all_names = slice_members(src, "AllKinds")
    view_names = slice_members(src, "ViewKinds")
    for n in all_names + view_names:
        if n not in consts:
            sys.exit(f"gen_event_kinds: AllKinds/ViewKinds names Kind{n}, which is "
                     f"not declared in {BUS.name}")

    lines = [
        "// GENERATED by scripts/gen_event_kinds.py from internal/store/bus.go.",
        "// Do not edit: `make check` fails when this file and the Go constants",
        "// disagree. Add a kind there and regenerate.",
        "//",
        "// The SSE stream names every frame (`event: <kind>`) and EventSource has no",
        "// wildcard listener, so a kind missing from EVENT_KINDS is not merely",
        "// unfiltered — it never arrives at all.",
        "",
        "/** Every kind the bus can carry. Subscribe to all of them. */",
        "export const EVENT_KINDS = [",
    ]
    lines += [f"  {consts[n][0]!r}," for n in all_names]
    lines += [
        "];",
        "",
        "/** The kinds a user may filter: things that happened to the PLATFORM.",
        " *",
        " * `dropped` is deliberately absent — it reports that THIS browser fell",
        " * behind, so hiding it would hide that the log is incomplete.",
        " */",
        "export const VIEW_KINDS = [",
    ]
    lines += [f"  {consts[n][0]!r}," for n in view_names]
    lines += [
        "];",
        "",
        "/** What each kind means, for tooltips and for anyone reading this file. */",
        "export const KIND_DOC = {",
    ]
    lines += [f"  {consts[n][0]!r}: {consts[n][1]!r}," for n in all_names]
    lines += ["};", ""]
    return "\n".join(lines).replace("'", "'")


def main() -> int:
    want = render()
    if "--check" in sys.argv:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have != want:
            print(f"{OUT.relative_to(ROOT)} is out of date — run "
                  f"scripts/gen_event_kinds.py", file=sys.stderr)
            return 1
        print(f"event kinds: {OUT.relative_to(ROOT)} matches internal/store/bus.go")
        return 0
    OUT.write_text(want, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
