#!/usr/bin/env python3
"""Record framework-conformance results and generate the committed matrix.

    ./run.py                 rewrite docs/conformance-matrix.md from the
                             committed out/*.json (no compose, no go test)
    ./run.py --backend sail --live
                             run that backend, record contract 4, rewrite
                             the matrix from all three JSON files
    ./run.py --check         fail if the generated matrix differs from what
                             is committed (CI mode; no compose)

Modelled on e2e/engine-matrix/run.py: the matrix is generated, never edited
by hand, so a cell cannot drift from the JSON that produced it. A ❌ is
allowed — the kit lands before every contract passes — but check_conformance.py
refuses one without a pointer.

`--live` is what makes a cell real. sail/jvm run a notebook through
RunNotebook and confirm out of band; warehouse runs the contracts as Go
tests against a real SQL Server over the emulator's TDS relay, each cell
recorded from its OWN `--- PASS:` line rather than from the process exit
code. Without --live the committed JSON is left alone, so a laptop render
cannot overwrite a CI-recorded pass with an offline gap.
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

DIR = Path(__file__).resolve().parent
REPO = DIR.parent.parent
OUT = DIR / "out"
MATRIX = REPO / "docs" / "conformance-matrix.md"

# Imported after DIR so `python e2e/conformance/run.py` works from the repo
# root without installing a package.
sys.path.insert(0, str(DIR))
from probes import BACKENDS, CONTRACTS, Result, record  # noqa: E402


def cell(result: dict | None) -> str:
    if result is None or result.get("status") == "na":
        return "—"
    status = result.get("status")
    if status == "pass":
        return "✅"
    err = result.get("error") or "failed"
    pointer = result.get("pointer") or ""
    # Truncate the reason so a long engine message does not blow the table;
    # the pointer is the actionable half.
    reason = err[:70]
    if pointer:
        num = result.get("id", "")
        return f"❌ {reason} ([§{num}]({pointer}))"
    return f"❌ {reason}"


def load(backend: str) -> dict[str, dict]:
    path = OUT / f"{backend}.json"
    if not path.exists():
        raise SystemExit(f"no results for {backend}: {path} missing")
    return {r["id"]: r for r in json.loads(path.read_text(encoding="utf-8"))}


def render() -> str:
    by_backend = {b: load(b) for b in BACKENDS}
    # Row order is the sail file's; the three files are generated together
    # from the same CONTRACTS list, so they agree.
    order = [r["id"] for r in json.loads((OUT / "sail.json").read_text(encoding="utf-8"))]
    lines = [
        "# Framework conformance matrix",
        "",
        "**Generated by `e2e/conformance/run.py`. Do not edit by hand.**",
        "",
        "Each cell is one contract on one backend. A ✅ means the contract was",
        "proven by executing on that backend and verifying **out of band** —",
        "the engine that wrote is never the one that confirms. A ❌ is a known",
        "gap with a pointer to the prose that closes it, not a silent skip.",
        "`—` is n/a: contracts 1–3 are notebook-session properties, and the",
        "Warehouse surface has none.",
        "",
        "Witnesses: `ci:conformance-sail`, `ci:conformance-jvm`,",
        "`ci:conformance-warehouse`. The contracts themselves are defined in",
        "[38-framework-conformance.md](38-framework-conformance.md).",
        "",
        "Every ✅ below was recorded by a live run. The lakehouse columns",
        "execute notebooks through RunNotebook and confirm through OneLake; the",
        "warehouse column runs T-SQL through the emulator's TDS relay against a",
        "real SQL Server and confirms on a connection that is not the one that",
        "wrote. A ✅ is that out-of-band reader, never the writer's own catalog.",
        "",
        "| # | Contract | sail | jvm | warehouse |",
        "|---|---|---|---|---|",
    ]
    for cid in order:
        sail = by_backend["sail"].get(cid)
        title = (sail or {}).get("contract", cid)
        lines.append(
            f"| {cid} | {title} | {cell(sail)} | "
            f"{cell(by_backend['jvm'].get(cid))} | "
            f"{cell(by_backend['warehouse'].get(cid))} |"
        )
    lines.append("")
    return "\n".join(lines)


def write_backend(backend: str, rows: list[dict]) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{backend}.json"
    path.write_text(json.dumps(rows, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path}", flush=True)


def ensure_out_writable() -> None:
    """Make `out/` writable by whatever uid the client container runs as.

    Copied from e2e/engine-matrix/run.py: the bind-mounted `out/` is owned by
    the checkout user, and an existing tracked file is 644. chmod the
    directory *and* the files, or a container that is not the checkout uid
    dies on truncate after the measuring is done.
    """
    OUT.mkdir(parents=True, exist_ok=True)
    os.chmod(OUT, 0o777)
    for existing in OUT.glob("*.json"):
        os.chmod(existing, 0o666)


def run_compose(backend: str) -> int:
    compose = ["docker", "compose", "-f", str(DIR / f"docker-compose.{backend}.yml")]
    ensure_out_writable()
    print(f"==> live write-landing on {backend}", flush=True)
    try:
        result = subprocess.run(
            compose + ["up", "--build", "--abort-on-container-exit",
                       "--exit-code-from", "client"],
            cwd=DIR)
        if result.returncode != 0:
            subprocess.run(compose + ["logs", "fabric-emulator", "spark-agent", "client"],
                           cwd=DIR)
        return result.returncode
    finally:
        subprocess.run(compose + ["down", "-v"], cwd=DIR,
                       stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


# The warehouse leg of each contract, and the Go test that proves it. Contracts
# 1-3 are absent because they are n/a here: they are properties of a notebook
# session and this surface has none.
#
# ONE `go test` INVOCATION, not four. They share a cold SQL Server start, and
# four processes would each pay for it; more importantly a single -v transcript
# is one artifact to read when a cell goes red.
WAREHOUSE_TESTS: dict[int, str] = {
    4: "TestConformanceWriteLanding",
    5: "TestConformanceConcurrentIsolation",
    6: "TestConformanceFallThrough",
    7: "TestConformanceCredentialLifetime",
}


def parse_go_verdicts(transcript: str) -> dict[str, str]:
    """Per-test PASS/FAIL/SKIP from a `go test -v` transcript.

    Pure, and separate from the subprocess, because this is where a skip could
    be mistaken for a pass and that decision has to be testable without a SQL
    Server. `--- PASS: TestX (0.5s)` -> {"TestX": "PASS"}.
    """
    out: dict[str, str] = {}
    for line in transcript.splitlines():
        stripped = line.strip()
        for word in ("PASS", "FAIL", "SKIP"):
            prefix = f"--- {word}: "
            if stripped.startswith(prefix):
                out[stripped[len(prefix):].split(" ")[0]] = word
    return out


def warehouse_results(verdicts: dict[str, str],
                      returncode: int) -> tuple[dict[int, Result], bool]:
    """One Result per warehouse contract, and whether any of them failed.

    A SKIP IS A GAP, NEVER A PASS. Without -v a skipped test exits 0 and is
    indistinguishable from a green, which is a writer-confirmed nothing.

    NO VERDICT IS ITS OWN CASE. A test the transcript never mentions did not
    report — the process died before reaching it — and that is not the same as
    the contract failing. Recording it as a plain failure would claim an
    assertion ran when none did.
    """
    live: dict[int, Result] = {}
    failed = False
    for num, test in WAREHOUSE_TESTS.items():
        title = CONTRACTS[num - 1][1]
        pointer = CONTRACTS[num - 1][2]
        verdict = verdicts.get(test)
        if verdict == "PASS":
            live[num] = Result(id=str(num), contract=title,
                               backend="warehouse", status="pass")
            continue
        failed = True
        if verdict == "SKIP":
            error = f"{test} skipped — set WAREHOUSE_MSSQL_DSN"
        elif verdict == "FAIL":
            error = f"{test} failed — see the go test transcript"
        else:
            error = f"{test} produced no verdict (go test exited {returncode})"
        live[num] = Result(id=str(num), contract=title, backend="warehouse",
                           status="fail", error=error, pointer=pointer)
    return live, failed


def run_warehouse_live() -> int:
    """Run the warehouse contracts and record each cell from its own verdict.

    PER-TEST VERDICTS, NOT THE PROCESS EXIT CODE. `go test` exits non-zero if
    any test fails, and reading that as "the warehouse failed" would turn one
    red cell into four — the same collapse the jvm hang produced before contract
    6 was gated. `--- PASS:` / `--- FAIL:` / `--- SKIP:` per test is what gets
    recorded.

    A SKIP IS RECORDED AS A GAP, never as a pass. Without -v a skipped test
    exits 0 and is indistinguishable from a green, which is a writer-confirmed
    nothing.
    """
    names = "|".join(WAREHOUSE_TESTS.values())
    cmd = ["go", "test", "./internal/server/",
           "-run", f"^({names})$",
           # Contract 7 is a 75s wait by construction, so the ceiling has to
           # clear it with room for a cold backend rather than being tuned to
           # the fast contracts.
           "-count=1", "-timeout", "600s", "-v"]
    print("==> live warehouse contracts", flush=True)
    proc = subprocess.run(cmd, cwd=REPO, text=True, capture_output=True)
    sys.stdout.write(proc.stdout)
    sys.stderr.write(proc.stderr)
    verdicts = parse_go_verdicts(proc.stdout + proc.stderr)
    live, failed = warehouse_results(verdicts, proc.returncode)
    write_backend("warehouse", record("warehouse", live=live))
    return (proc.returncode or 1) if failed else 0


def run_live(backend: str) -> int:
    if backend == "warehouse":
        return run_warehouse_live()
    return run_compose(backend)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--backend", choices=BACKENDS)
    ap.add_argument("--live", action="store_true",
                    help="run the backend and record its contracts out of band")
    ap.add_argument("--check", action="store_true",
                    help="fail if the generated matrix differs from the committed one")
    args = ap.parse_args()

    if args.live and not args.check:
        for backend in ([args.backend] if args.backend else BACKENDS):
            code = run_live(backend)
            if code != 0:
                return code

    generated = render()
    if args.check:
        current = MATRIX.read_text(encoding="utf-8") if MATRIX.exists() else ""
        if current != generated:
            print("docs/conformance-matrix.md is out of date — regenerate with "
                  "e2e/conformance/run.py", file=sys.stderr)
            return 1
        print("conformance matrix is current")
        return 0
    MATRIX.write_text(generated, encoding="utf-8")
    print(f"wrote {MATRIX}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
