#!/usr/bin/env python3
"""Record framework-conformance results and generate the committed matrix.

    ./run.py                 record every backend (offline gaps) and rewrite
                             docs/conformance-matrix.md
    ./run.py --backend sail  record one backend; rewrite the matrix from all
                             three committed JSON files
    ./run.py --check         fail if the generated matrix differs from what
                             is committed (CI mode)

Modelled on e2e/engine-matrix/run.py: the matrix is generated, never edited
by hand, so a cell cannot drift from the JSON that produced it. A ❌ is
allowed — the kit lands before every contract passes — but check_conformance.py
refuses one without a pointer.

Live backends are not started here. Contract 4's assertion (writer ≠ reader)
is in probes.py and is unit-tested; wiring compose is the next change. Until
then every required/control cell is a known gap with a pointer into docs/38.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

DIR = Path(__file__).resolve().parent
OUT = DIR / "out"
MATRIX = DIR.parent.parent / "docs" / "conformance-matrix.md"

# Imported after DIR so `python e2e/conformance/run.py` works from the repo
# root without installing a package.
sys.path.insert(0, str(DIR))
from probes import BACKENDS, record  # noqa: E402


def cell(result: dict | None) -> str:
    if result is None or result.get("status") == "na":
        return "—"
    status = result.get("status")
    if status == "pass":
        return "✅"
    err = result.get("error") or "failed"
    pointer = result.get("pointer") or ""
    # Truncate the reason so a long engine message does not blow the table;
    # the pointer is the actionable half.
    reason = err[:70]
    if pointer:
        num = result.get("id", "")
        return f"❌ {reason} ([§{num}]({pointer}))"
    return f"❌ {reason}"


def load(backend: str) -> dict[str, dict]:
    path = OUT / f"{backend}.json"
    if not path.exists():
        raise SystemExit(f"no results for {backend}: {path} missing")
    return {r["id"]: r for r in json.loads(path.read_text(encoding="utf-8"))}


def render() -> str:
    by_backend = {b: load(b) for b in BACKENDS}
    # Row order is the sail file's; the three files are generated together
    # from the same CONTRACTS list, so they agree.
    order = [r["id"] for r in json.loads((OUT / "sail.json").read_text(encoding="utf-8"))]
    lines = [
        "# Framework conformance matrix",
        "",
        "**Generated by `e2e/conformance/run.py`. Do not edit by hand.**",
        "",
        "Each cell is one contract on one backend. A ✅ means the contract was",
        "proven by executing on that backend and verifying **out of band** —",
        "the engine that wrote is never the one that confirms. A ❌ is a known",
        "gap with a pointer to the prose that closes it, not a silent skip.",
        "`—` is n/a: contracts 1–3 are notebook-session properties, and the",
        "Warehouse surface has none.",
        "",
        "Witnesses: `ci:conformance-sail`, `ci:conformance-jvm`,",
        "`ci:conformance-warehouse`. The contracts themselves are defined in",
        "[38-framework-conformance.md](38-framework-conformance.md).",
        "",
        "Contract 4 (write landing) is the first asserted row: the harness",
        "refuses a writer that confirms its own write. Live backends have not",
        "yet recorded a pass; the cell stays ❌ until they do.",
        "",
        "| # | Contract | sail | jvm | warehouse |",
        "|---|---|---|---|---|",
    ]
    for cid in order:
        sail = by_backend["sail"].get(cid)
        title = (sail or {}).get("contract", cid)
        lines.append(
            f"| {cid} | {title} | {cell(sail)} | "
            f"{cell(by_backend['jvm'].get(cid))} | "
            f"{cell(by_backend['warehouse'].get(cid))} |"
        )
    lines.append("")
    return "\n".join(lines)


def write_backend(backend: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / f"{backend}.json"
    path.write_text(json.dumps(record(backend), indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path}", flush=True)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--backend", choices=BACKENDS)
    ap.add_argument("--check", action="store_true",
                    help="fail if the generated matrix differs from the committed one")
    args = ap.parse_args()

    if not args.check:
        for backend in ([args.backend] if args.backend else BACKENDS):
            write_backend(backend)

    generated = render()
    if args.check:
        current = MATRIX.read_text(encoding="utf-8") if MATRIX.exists() else ""
        if current != generated:
            print("docs/conformance-matrix.md is out of date — regenerate with "
                  "e2e/conformance/run.py", file=sys.stderr)
            return 1
        print("conformance matrix is current")
        return 0
    MATRIX.write_text(generated, encoding="utf-8")
    print(f"wrote {MATRIX}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
