"""Tests for the landing page's data assembly and its no-typed-numbers check.

WHAT IS ACTUALLY AT RISK HERE. The script has two halves and they fail in
opposite directions:

  * The COPY half is loud. If a manifest is missing or a key has gone, it
    raises and the build stops.
  * The CHECK half — "refuse a page that hardcodes a total" — fails SILENT. A
    regex that stops matching reports no problem, which is indistinguishable
    from a page with no problem. That is the same shape as the defect this
    script exists to prevent, one level up: the published page carried "113
    supported capability claims" for weeks because nothing said otherwise.

So every check-half test below drives a page it MUST refuse, and the passing
page is the single control. A test that only fed it good input would stay green
through the deletion of the check.

The parsers are tested on their own minimal tables rather than on the repo's
generated matrices: the matrices are regenerated by other tooling, and a test
that reads them asserts today's content rather than the parser's behaviour.
"""
import json
import pathlib
import sys

import pytest

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "scripts"))

import build_landing_data as c  # noqa: E402

# A page that satisfies every rule. Each test below mutates ONE thing.
GOOD_PAGE = """\
---
import stats from '../data/site-stats.json';
const num = (n) => n.toLocaleString('en');
---
<header>
  {/* stats:start - every figure below must be an expression, never a typed
      number. */}
  <div class="stats">
    <div class="stat"><b>{num(p.real)}</b><span>graded real, of {num(p.total)}</span></div>
    <div class="stat"><b>{num(w.total)}</b><span>witnesses</span></div>
    <div class="stat"><b>{num(stats.docs)}</b><span>pages</span></div>
  </div>
  {/* stats:end */}
</header>
"""

ENGINE_MD = """\
# Engine matrix

| Capability | Sail | Sail (emulator) | JVM overlay |
|---|---|---|---|
| Delta write | ✅ | ✅ | ✅ |
| Time travel | ❌ | ✅ | ✅ |
| Java UDF | ❌ | ❌ | ✅ |
"""

CONFORMANCE_MD = """\
# Conformance

| # | Contract | Sail | Warehouse | KQL |
|---|---|---|---|---|
| 1 | Reads a table | ✅ | ✅ | — |
| 2 | Writes a table | ✅ | ❌ | — |
| 3 | Streams | ❌ | — | ✅ |
"""

WITNESSES = {
    "_gated": {"note": "not a claim"},
    "a-claim": {"witnesses": ["ci:warehouse-tds", "go:TestThing"]},
    "compared-against-a-tenant": {"witnesses": ["ci:real-fabric"]},
    "no-witness-list": {},
}

STATS = {
    "parity": {"real": 138, "total": 158},
    "witnesses": {"claims": 126, "distinct": 231},
    "e2e": 63,
}


@pytest.fixture
def page(tmp_path):
    """Write a landing page, optionally with one substitution applied."""

    def build(old=None, new="", body=GOOD_PAGE):
        if old is not None:
            assert old in body, f"the fixture no longer contains {old!r}"
            body = body.replace(old, new)
        path = tmp_path / "index.astro"
        path.write_text(body, encoding="utf-8")
        return path

    return build


@pytest.fixture
def sources(tmp_path, monkeypatch):
    """Point the module's inputs at files this test controls."""

    def build(engine=ENGINE_MD, conformance=CONFORMANCE_MD, witnesses=WITNESSES,
              stats=STATS, write_stats=True):
        (tmp_path / "engine.md").write_text(engine, encoding="utf-8")
        (tmp_path / "conformance.md").write_text(conformance, encoding="utf-8")
        (tmp_path / "witnesses.json").write_text(json.dumps(witnesses), encoding="utf-8")
        monkeypatch.setattr(c, "ENGINE_MATRIX", tmp_path / "engine.md")
        monkeypatch.setattr(c, "CONFORMANCE", tmp_path / "conformance.md")
        monkeypatch.setattr(c, "WITNESSES", tmp_path / "witnesses.json")
        site_stats = tmp_path / "site-stats.json"
        if write_stats:
            site_stats.write_text(json.dumps(stats), encoding="utf-8")
        monkeypatch.setattr(c, "SITE_STATS", site_stats)
        # ROOT is deliberately left alone. tmp_path is outside the repo, so
        # every failure message these provoke names a path ROOT does not
        # contain, which is the case `shown()` exists to survive.

    return build


# --- rendering a path inside a failure message -----------------------------

def test_a_path_inside_the_repo_is_shortened():
    assert c.shown(c.ROOT / "docs" / "witnesses.json") == "docs/witnesses.json"


def test_a_path_outside_the_repo_is_shown_whole(tmp_path):
    # `Path.relative_to` raises for anything outside ROOT, and every caller is
    # inside a failure message. Without the fallback the branch whose job is to
    # explain a problem replaces the explanation with a pathlib traceback.
    outside = tmp_path / "witnesses.json"
    assert c.shown(outside) == outside.as_posix()


def test_a_message_reads_the_same_on_every_platform(monkeypatch):
    # This suite runs on three operating systems, and `str()` on a Windows path
    # renders backslashes, so one failure would read two ways depending on the
    # runner. Driven with pure Windows paths so the case is exercised wherever
    # this happens to run, rather than only on the platform that has the bug.
    root = pathlib.PureWindowsPath(r"D:\a\fabric-emulator\fabric-emulator")
    monkeypatch.setattr(c, "ROOT", root)
    assert c.shown(root / "docs" / "witnesses.json") == "docs/witnesses.json"
    assert c.shown(pathlib.PureWindowsPath(r"C:\elsewhere\x.json")) == "C:/elsewhere/x.json"


def test_a_failure_message_survives_a_path_outside_the_repo(sources, tmp_path):
    # The same thing through a real error branch: what a reader gets is the
    # diagnosis, not a ValueError raised from inside the reporting.
    sources(witnesses={"_gated": {}})
    with pytest.raises(SystemExit) as excinfo:
        c.real_tenant_claims()
    assert (tmp_path / "witnesses.json").as_posix() in str(excinfo.value)


# --- the check half: every case is a page it must refuse -------------------


def test_the_good_page_passes(page):
    """The control. Without it the refusals below prove only that it refuses."""
    assert c.check_page(page()) == (0, "")


def test_a_page_that_does_not_exist(tmp_path):
    code, message = c.check_page(tmp_path / "nope.html")
    assert code == 1
    assert "does not exist" in message


def test_a_page_with_no_stats_region(page):
    code, message = c.check_page(page(old="{/* stats:end */}", new=""))
    assert code == 1
    assert "stats:start" in message


def test_a_typed_number_where_an_expression_belongs(page):
    """The defect this whole script exists for.

    These docs said "113 supported capability claims" long after the figure was
    120. Astro cannot prevent somebody typing the number; this can.
    """
    code, message = c.check_page(
        page(old="<b>{num(p.real)}</b>", new="<b>139</b>"))
    assert code == 1
    assert "'<b>139</b>'" in message or "139" in message
    assert "typed number" in message


def test_a_number_typed_beside_an_expression_is_still_caught(page):
    """Half-interpolated is not interpolated: the literal still goes stale."""
    code, message = c.check_page(
        page(old="<b>{num(w.total)}</b>", new="<b>{num(w.total)} of 159</b>"))
    assert code == 1
    assert "typed number" in message


def test_a_page_that_stopped_importing_the_manifest(page):
    code, message = c.check_page(
        page(old="import stats from '../data/site-stats.json';", new=""))
    assert code == 1
    assert "site-stats.json" in message


def test_a_manifest_named_only_in_a_comment_is_not_read(page):
    """The mutation that beat the first version of this check.

    Renaming the import left the old filename in a comment above it, and a
    substring search called that "still reads it".
    """
    code, message = c.check_page(page(
        old="import stats from '../data/site-stats.json';",
        new="// site-stats.json used to be imported here\nimport stats from './other.json';"))
    assert code == 1
    assert "site-stats.json" in message


@pytest.mark.parametrize("spelling", ["load('x.json')", 'fetch("x.json")', "fetch( 'x.json'"])
def test_fetches_accepts_the_spellings_the_page_uses(spelling):
    assert c.fetches(spelling, "x.json")


def test_fetches_rejects_a_bare_mention():
    assert not c.fetches("// x.json is the manifest", "x.json")
    assert not c.fetches("const name = 'x.json';", "x.json")


# --- the parsers ------------------------------------------------------------


def test_table_rows_skips_separators_and_prose():
    rows = list(c.table_rows(ENGINE_MD))
    assert rows[0][0] == "Capability"
    assert len(rows) == 4  # header + three probes, no |---| rule


def test_engine_matrix_counts_a_pass_per_column(sources):
    sources()
    matrix = c.engine_matrix()
    assert matrix["probes"] == 3
    assert matrix["columns"] == ["Sail", "Sail (emulator)", "JVM overlay"]
    assert matrix["passes"] == {"Sail": 1, "Sail (emulator)": 2, "JVM overlay": 3}


def test_engine_matrix_skips_a_row_that_does_not_match_the_header(sources):
    """The width guard is load-bearing, not defensive tidiness.

    `zip(columns, cells[1:], strict=True)` below RAISES on a row with the wrong
    number of cells, so without the guard one malformed line in a generated
    matrix takes down the docs deploy with a ValueError instead of publishing.
    """
    sources(engine=ENGINE_MD + "| ragged | ✅ |\n")
    assert c.engine_matrix()["probes"] == 3


def test_engine_matrix_refuses_a_matrix_it_could_not_parse(sources):
    """A parse that yields nothing is a failure, not a zero.

    Zero would flow through to the page as a legible "0 of 0", which reads as
    an answer.
    """
    sources(engine="# Engine matrix\n\nNo table here.\n")
    with pytest.raises(SystemExit, match="no probes parsed"):
        c.engine_matrix()


def test_conformance_excludes_the_inapplicable_cells(sources):
    """An em dash means the contract does not apply, not that it failed."""
    sources()
    assert c.conformance() == {"contracts": 3, "proven": 4, "applicable": 6}


def test_conformance_refuses_a_matrix_it_could_not_parse(sources):
    sources(conformance="# Conformance\n\n| a | b |\n|---|---|\n| x | y |\n")
    with pytest.raises(SystemExit, match="no contracts parsed"):
        c.conformance()


def test_real_tenant_claims_counts_only_a_real_tenant_witness(sources):
    sources()
    assert c.real_tenant_claims() == 1


def test_real_tenant_claims_ignores_the_gated_declaration(sources):
    """`_gated` is a declaration block, not a claim, and has no witnesses key."""
    sources(witnesses={"_gated": {"note": "only this"}})
    with pytest.raises(SystemExit, match="no claims parsed"):
        c.real_tenant_claims()


def test_zero_real_tenant_claims_is_an_answer_not_a_failure(sources):
    """Today's true value. It must come out as 0, not as an error or a dash."""
    sources(witnesses={"a-claim": {"witnesses": ["go:TestThing"]}})
    assert c.real_tenant_claims() == 0


def test_site_stats_is_read_not_recomputed(sources):
    sources()
    assert c.site_stats()["parity"]["real"] == 138


def test_site_stats_missing_names_the_build_that_writes_it(sources):
    sources(write_stats=False)
    with pytest.raises(SystemExit, match="does not exist"):
        c.site_stats()


@pytest.mark.parametrize(
    "stats",
    [
        {"parity": {"total": 158}, "witnesses": {"claims": 1, "distinct": 1}, "e2e": 1},
        {"parity": {"real": 1, "total": 1}, "witnesses": {"claims": 1}, "e2e": 1},
        {"parity": {"real": 1, "total": 1}, "witnesses": {"claims": 1, "distinct": 1}},
        {"parity": "not a mapping", "witnesses": {"claims": 1, "distinct": 1}, "e2e": 1},
    ],
)
def test_a_generator_that_stops_counting_fails_here_not_on_the_page(sources, stats):
    """The symptom on the published page is a dash, which nobody reports."""
    sources(stats=stats)
    with pytest.raises(SystemExit, match="no longer carries"):
        c.site_stats()


# --- end to end -------------------------------------------------------------


def test_main_writes_both_manifests(sources, page, tmp_path, monkeypatch, capsys):
    sources()
    out = tmp_path / "_site"
    monkeypatch.setattr(sys, "argv", [
        "build_landing_data.py", "--out", str(out), "--landing", str(page())])

    assert c.main() == 0

    stats = json.loads((out / "site-stats.json").read_text(encoding="utf-8"))
    evidence = json.loads((out / "evidence-summary.json").read_text(encoding="utf-8"))
    assert stats == STATS
    assert evidence["conformance"]["proven"] == 4
    assert evidence["real_tenant"] == 1
    # The emulator column is the one a user actually gets, so it is the one
    # quoted: 2 of 3, not bare Sail's 1 and not the overlay's 3.
    assert "2/3 engine probes pass" in capsys.readouterr().out


def test_main_refuses_before_writing_anything(sources, page, tmp_path, monkeypatch, capsys):
    """A refused page must not leave a half-built _site behind."""
    sources()
    out = tmp_path / "_site"
    bad = page(old="<b>{num(p.real)}</b>", new="<b>139</b>")
    monkeypatch.setattr(sys, "argv", [
        "build_landing_data.py", "--out", str(out), "--landing", str(bad)])

    assert c.main() == 1
    assert not out.exists()
    assert "typed number" in capsys.readouterr().out


def test_the_real_landing_page_satisfies_its_own_check():
    """The one case that reads the repository.

    Everything above drives synthetic pages, which proves the checker works and
    says nothing about what is published. This is the control in the other
    direction: the page actually in the tree must pass.
    """
    landing = c.ROOT / "website" / "src" / "pages" / "index.astro"
    # NOT skipped when absent. This is the only test that reads what is
    # actually published, and a skip here would look identical to a pass on the
    # day somebody moves the hero.
    assert landing.exists(), f"{landing} is missing; the hero this checks is gone"
    code, message = c.check_page(landing)
    assert code == 0, message
