import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { remarkMermaid } from './plugins/remark-mermaid.mjs';

// Project GitHub Pages site: https://calvinchengx.github.io/fabric-emulator/
export default defineConfig({
  site: 'https://calvinchengx.github.io',
  base: '/fabric-emulator/',
  // Docs were renumbered into reading order; keep the old published URLs alive.
  redirects: {
    '/01-architecture/': '/fabric-emulator/03-architecture/',
    '/02-api-surface/': '/fabric-emulator/07-control-plane-api/',
    '/03-roadmap/': '/fabric-emulator/13-roadmap/',
    '/04-real-compute/': '/fabric-emulator/14-real-compute/',
  },
  // remarkMermaid turns ```mermaid fences into <pre class="mermaid"> before
  // Expressive Code sees them; src/components/Head.astro renders them client-side.
  markdown: {
    remarkPlugins: [remarkMermaid],
  },
  integrations: [
    starlight({
      title: 'Fabric Emulator',
      components: {
        Head: './src/components/Head.astro',
      },
      description:
        'A local emulator of the Microsoft Fabric control plane — workspaces, items, RBAC, git integration, and long-running operations — that validates Entra bearer tokens.',
      social: [
        { icon: 'github', label: 'GitHub', href: 'https://github.com/calvinchengx/fabric-emulator' },
      ],
      editLink: {
        baseUrl: 'https://github.com/calvinchengx/fabric-emulator/edit/main/docs/',
      },
      sidebar: [
        {
          label: 'Getting started',
          items: [
            { slug: 'index' },
            { slug: '01-quickstart' },
            { slug: '02-installation' },
            { slug: '03-architecture' },
            { slug: '04-configuration' },
            { slug: '05-tls-and-hosts' },
          ],
        },
        {
          label: 'Reference',
          items: [
            { slug: '06-data-model-and-seed' },
            { slug: '07-control-plane-api' },
            { slug: '08-onelake' },
            { slug: '09-identity-handshake' },
          ],
        },
        {
          label: 'Testing',
          items: [
            { slug: '10-testing' },
            { slug: '11-testing-with-fabric-cicd' },
            { slug: '12-e2e-matrix' },
          ],
        },
        {
          label: 'Project',
          items: [
            { slug: '13-roadmap' },
            { slug: '14-real-compute' },
            { slug: '15-entra-companion' },
            { slug: '16-warehouse-tds' },
            { slug: '17-parity' },
            { slug: '18-semantic-model-references' },
            { slug: '19-semantic-model-plan' },
          ],
        },
        {
          // Pages generated by scripts/parity-versions.mjs from git release
          // tags. The index lists every per-version snapshot, so it doubles as
          // the version browser (this Starlight's sidebar has no autogenerate).
          label: 'Parity history',
          items: [{ slug: 'parity-history' }, { slug: 'parity-history/changelog' }],
        },
      ],
    }),
  ],
});
